### ISSUE TITLE
I tried test with my shiny new M1 pro

### ISSUE THREAD

**Issue by hannesa2** [tkshirakawa/benchmark_TensorFlow_macOS#3]
```
cd Downloads
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh
chmod +x ~/Downloads/Miniforge3-MacOSX-arm64.sh
sh ~/Downloads/Miniforge3-MacOSX-arm64.sh
source ~/miniforge3/bin/activate
python -m pip uninstall tensorflow-macos
python -m pip uninstall tensorflow-metal
conda install -c apple tensorflow-deps
conda install -c apple tensorflow-deps==2.6.0
python -m pip install tensorflow-macos
python -m pip install tensorflow-metal
cd
git clone git@github.com:tkshirakawa/benchmark_TensorFlow_macOS.git
cd benchmark_TensorFlow_macOS
python Train.py
```

but run into

```
Traceback (most recent call last):
  File "/Users/hannes/miniforge3/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/Users/hannes/miniforge3/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Users/hannes/miniforge3/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/hannes/miniforge3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libcblas.3.dylib
  Referenced from: /Users/hannes/miniforge3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so
  Reason: tried: '/Users/hannes/miniforge3/lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/python3.9/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/python3.9/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/bin/../lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/bin/../lib/libcblas.3.dylib' (no such file), '/usr/local/lib/libcblas.3.dylib' (no such file), '/usr/lib/libcblas.3.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hannes/git/benchmark_TensorFlow_macOS/Train.py", line 51, in <module>
    _LM = imm.SourceFileLoader('Loss_and_metrics', loss_metrics_path).load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/hannes/git/benchmark_TensorFlow_macOS/utils/Loss_and_metrics.py", line 14, in <module>
    import tensorflow as tf
  File "/Users/hannes/miniforge3/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/hannes/miniforge3/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/Users/hannes/miniforge3/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    import numpy as np
  File "/Users/hannes/miniforge3/lib/python3.9/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/Users/hannes/miniforge3/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/Users/hannes/miniforge3/bin/python"
  * The NumPy version is: "1.19.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/hannes/miniforge3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libcblas.3.dylib
  Referenced from: /Users/hannes/miniforge3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so
  Reason: tried: '/Users/hannes/miniforge3/lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/python3.9/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/python3.9/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/bin/../lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/lib/libcblas.3.dylib' (no such file), '/Users/hannes/miniforge3/bin/../lib/libcblas.3.dylib' (no such file), '/usr/local/lib/libcblas.3.dylib' (no such file), '/usr/lib/libcblas.3.dylib' (no such file)
```

```
python --version
Python 3.9.7
```

Do you have any idea ?

**Comment by tkshirakawa** [comment]
Hi, hannesa2
Thank you for your comment.
In my experience, it seems that numpy and/or other packages such as opencv etc should be installed to the miniforge3 BEFORE installing ‘tensorflow-deps’, ‘tensorflow-macos’ and ‘tensorflow-metal’.

The following packages are required for this benchmark code. The other packages will be installed based on their dependencies.
numpy
h5py
hdf5
joblib
opencv
graphviz

As for versions, please refer to my package list ‘miniforge3_TF26_macOS_Monterey.txt’ released in <https://github.com/tkshirakawa/benchmark_TensorFlow_macOS/tree/main/package_list>

You may be able to install the packages directly into your env by
`conda install --name [env_name] --file miniforge3_TF26_macOS_Monterey.txt`
But it may be dependent on machine-specific things, which may be UNSAFE.

**Comment by hannesa2** [comment]
Thanks for your response.  As you can see, I'm a bloody beginner.

I did again
```
conda install -c apple tensorflow-deps
python -m pip uninstall tensorflow-macos
python -m pip uninstall tensorflow-metal
conda install -c apple tensorflow-deps --force-reinstall
conda install -c apple tensorflow-deps==2.6.0
python -m pip install tensorflow-metal
python Train.py
```
Now the error is at least shorter

<img width="691" alt="image" src="https://user-images.githubusercontent.com/3314607/141091680-6139c816-d319-4910-b5d9-65b23fa9c154.png">

**Comment by tkshirakawa** [comment]
Hi
The package “tensorflow” is lost.
I guess you need
`python -m pip install tensorflow-macos`
before
`python -m pip install tensorflow-metal`

They are Step2 and 3 in the official site:
https://developer.apple.com/metal/tensorflow-plugin/

I pray for your success!

**Comment by hannesa2** [comment]
Thanks a lot, with the recommended change it works now
```
conda install -c apple tensorflow-deps
python -m pip uninstall tensorflow-macos
python -m pip uninstall tensorflow-metal
conda install -c apple tensorflow-deps --force-reinstall
conda install -c apple tensorflow-deps==2.6.0
python -m pip install tensorflow-macos # <-- new
python -m pip install tensorflow-metal
./run_BENCHMARK_5times_5min_interval.sh
```

The installation issue is gone ! 🎉 Thank you

**Comment by hannesa2** [comment]
Now I see a result on my mac 
<img width="457" alt="image" src="https://user-images.githubusercontent.com/3314607/158009939-fc26ec89-7551-45c5-8e3d-6e2ebb5c54cf.png">


```
- Starting model training...
---------------- Epoch 1/2 ----------------
[Image Data Generator] Training data from CSV : CSV dataset
[Image Data Generator] Validation data from CSV : CSV dataset
[Learning Rate Scheduler]
Polynomial decay : base_lr = 0.25, power = 0.9
Learning rate = 0.25 (raw LR = 0.25, LR multiplier = 1.0)
32/32 [||||||||||||||||||||||||||||||||||||||||] - 102.9 s, 3216 ms/batch : Loss 0.7204, mIoU 0.5496, Dice 0.6233 - done

Metrics for validation data in this epoch:
Recalculating 7/7 [||||||||||||||||||||||||||||||] 2.49 sec - done
[Averaged   ]  mIoU 0.946352, Dice 0.970691 : data length 500    / 100    

Val. mean IoU  = 0.946352 (updated from the value = -inf)
Val. Dice coef = 0.970691 (updated from the value = -inf)
 
Monitoring metrics for learning rate management... : updated
Count of update [1] - LR will rise/recover at [100] updates by step = 5.0
 
---------------- Epoch 2/2 ----------------
[Image Data Generator] Training data from CSV : CSV dataset
[Image Data Generator] Validation data from CSV : CSV dataset
[Learning Rate Scheduler]
Polynomial decay : base_lr = 0.25, power = 0.9
Learning rate = 0.13397168281703664 (raw LR = 0.13397168281703664, LR multiplier = 1.0)
32/32 [||||||||||||||||||||||||||||||||||||||||] - 81.5 s, 2547 ms/batch : Loss 0.0797, mIoU 0.9710, Dice 0.9845 - done

Metrics for validation data in this epoch:
Recalculating 7/7 [||||||||||||||||||||||||||||||] 2.05 sec - done
[Averaged   ]  mIoU 0.932872, Dice 0.959675 : data length 500    / 100    

Val. mean IoU  = 0.932872 (not updated, the current best = 0.946352)
Val. Dice coef = 0.959675 (not updated, the current best = 0.970691)
Patience count = 1 (early stop at 50 patience)
 
Monitoring metrics for learning rate management... : Not updated
Count of not-update [1] - LR will decay at [100] patiences by step = 0.1
 

==================================================================================================
Computation time        : 0:03:14.848346
From the date           : 2022-03-12 17:03:50.369163+09:00

==================================================================================================

```
